#{{ansible_managed}}
{% if project_type|lower == 'web' %}

FROM nginx:1.14
COPY dist/{{project}}/* /opt/app-root/src/
CMD ["nginx", "-g", "daemon off;"]
EXPOSE 8080

{% else %}

FROM openjdk:8-jdk
ENV APP_NAME {{project}}
ADD target/*.jar $APP_NAME.jar
ENTRYPOINT ["sh", "-c", "java $JAVA_OPTS -jar $APP_NAME.jar"]

{% endif %}
